name: GitHub Action Workflow With Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Cache npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        #restore-keys: |
         # ${{ runner.os }}-node-

    # Step 4: Install dependencies
    - name: Install dependencies
      working-directory: frontend
      run: npm install

    #- name: Save npm cache
    #  uses: actions/cache@v3
    #  with:
    #    path: ~/.npm
    #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
    # Step 5: List the cache content
    #- name: List npm cache contents
    #  run: |
    #    echo "Contents of ~/.npm:"
    #    ls -R ~/.npm
        
     # Step 6: Archive npm cache
    #- name: Archive npm cache
    #  run: |
     #   tar -czvf npm-cache.tar.gz -C ~/.npm .
      #  echo "npm cache archived."

    # Step 7: Upload npm cache as artifact
  #  - name: Upload npm cache artifact
    #  uses: actions/upload-artifact@v3
     # with:
        #name: npm-cache
      #  path: npm-cache.tar.gz
        
    # Step 5: Simple echo message
    - name: Simple echo message
      run: echo "GitHub Actions workflow executed successfully!"
